server:
  port: 9006
spring:
  application:
    name: dc-spit #指定服务名
  data:
    mongodb:
      host: 192.168.200.128
      database: dc-spit
  redis:
    host: 192.168.200.128
    timeout: 3000

### jwt 相关配置 ###
jwt:
  config:
    key: www.treeshell.cn