server: 
  port: 9004
spring: 
  application:  
    name: dc-article #指定服务名
  datasource:  
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.200.128:3306/dc_article?characterEncoding=utf-8
    username: root
    password: mysql
  jpa: 
    database: MySQL
    show-sql: true
mybatis-plus:
  mapper-location:- classpath: mapper/*Mapper.xml
  global-config:
    db-config:
      id-type: assign_id #自3.3.0开始,默认使用雪花算法+UUID
    banner: false